Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
    v.name = "tomcat-util"
  end

  config.vm.provision :shell, path: "mariadbinstall.sh"
  config.vm.provision :shell, path: "jdk11_tomcatinstall.sh"

  config.vm.network :forwarded_port, guest: 8080, host: 4000, host_ip: "127.0.0.1"
  config.vm.synced_folder "webapps/", "/home/vagrant/webapps"
end
